Add Project tab
ucgmsim/seistech_psha_frontend pull request #13
Opened 2020-11-26 02:50 UTC by SnowNooDLe

# Project tab

Now we have a project tab that interacts with dropdowns.

![image](https://user-images.githubusercontent.com/7849113/100300840-bc74cc80-2ffb-11eb-8855-1c3140823688.png)

Unlike the Hazard Analysis tab, users can choose from the dropdown we provided.

## Workflow

It is pretty much similar to Seismic Hazard.

![image](https://user-images.githubusercontent.com/7849113/100301153-6e13fd80-2ffc-11eb-9da1-f33f21f0a65c.png)

To get the **Regional and VS30 maps**, do the following steps

1. Choose the `Project ID`
2. Choose the `Location`
3. Choose the `VS30`
4. Click the `Get` button

![image](https://user-images.githubusercontent.com/7849113/100301173-7c621980-2ffc-11eb-8fc3-0263f6384354.png)

To get the **Hazard Curve**

1. Choose `Intensity Measure`
2. Click the `Get` button

To get the **Disaggergation**

1. Choose `Intensity Measure` first (No need to click Get button as we just need IM value)
2. Choose `Return Period` from the **Disaggregation** section
3. Click the `Get` button

To get the **UHS**

1. Choose `Return periods` from **Uniform Hazard Spectrum** (You can choose more than one but currently we only have one)
2. Click the `Get` button

## Site Selection

### Regional Map
![image](https://user-images.githubusercontent.com/7849113/100300915-e5955d00-2ffb-11eb-9c0c-5a097dd0820d.png)

### VS30 Map
![image](https://user-images.githubusercontent.com/7849113/100300932-ef1ec500-2ffb-11eb-9672-9c0e41a71a12.png)

## Seismic Hazard

### Hazard Curve

![image](https://user-images.githubusercontent.com/7849113/100300985-0d84c080-2ffc-11eb-8e2f-f86ee01ec9de.png)

![image](https://user-images.githubusercontent.com/7849113/100300996-12497480-2ffc-11eb-87a9-c0bf7fbb0f52.png)

### Disaggregation

![image](https://user-images.githubusercontent.com/7849113/100301018-1c6b7300-2ffc-11eb-8a7f-ca9e2597d3b9.png)

![image](https://user-images.githubusercontent.com/7849113/100301025-20979080-2ffc-11eb-80a0-53ed78c3ce66.png)

![image](https://user-images.githubusercontent.com/7849113/100301031-255c4480-2ffc-11eb-98a8-b428cbcad236.png)

### UHS

![image](https://user-images.githubusercontent.com/7849113/100301046-2db47f80-2ffc-11eb-982d-c24d94083386.png)

2020-11-27 00:39 UTC, jasonmotha requested changes

2020-11-27 00:39 UTC, jasonmotha commented on frontend/README.md
> +Users can choose one **Intensit Measure** from the dropdown, then click **Get** button to get the following plots.
spelling

2020-11-27 00:39 UTC, jasonmotha commented on frontend/src/components/Project/SiteSelection/SiteSelectionForm.js
> +          console.log(error);
Do these errors need the error modal?

2020-11-27 01:16 UTC, SnowNooDLe commented on frontend/README.md
> +Users can choose one **Intensit Measure** from the dropdown, then click **Get** button to get the following plots.
Good catch, I went through Grammarly and though was okay.

2020-11-27 01:25 UTC, SnowNooDLe commented on frontend/src/components/Project/SiteSelection/SiteSelectionForm.js
> +          console.log(error);
In regard to 'Error Modal', is this what you mean? 
![Screenshot from 2020-11-27 14-21-16](https://user-images.githubusercontent.com/7849113/100400567-de358880-30bb-11eb-8050-8a1df2d55748.png)

If so, I think things like these can be done when we add Tooltips ? as if it was for Viewer part (ex: GMS Viewer, Hazard Curve viewer) then they have a dedicated space to display a warning msg.

Whereas this part (sending a request to Project API to get data in JSON) and maybe getting IMs after we set location in Site Selection for Hazard Analysis, they only have a dropdown and disabled as we failed to fetch so the length of the option is 0 (As the option is an array for react-select)

2020-11-27 03:14 UTC, jasonmotha approved these changes

2020-11-29 19:26 UTC, claudio525 approved these changes

2020-11-29 19:26 UTC, claudio525 commented on frontend/README.md
> +But in EA and PROD.
This sentence seems incomplete?

2020-11-29 22:36 UTC, merged