NZS 1170
ucgmsim/seistech_psha_frontend pull request #14
Opened 2020-12-04 02:19 UTC by SnowNooDLe

# NZS1170

NZ Code is now separated, this is no longer part of the Hazard Curve nor UHS. (In terms of API calling).

## NZS1170 Section

We now have a dedicated section for NZS1170 and by setting the location from **Site Selection**, we also get the following default parameters:
1. Distance
2. Soil Class
3. Z Factor
However, only Soil Class and Z Factor are visible on the frontend. **Z Factor** is the user input with float, **Soil Class** is the dropdown with five options.

![image](https://user-images.githubusercontent.com/7849113/101111629-72fe3000-3640-11eb-8f66-58c485c44d63.png)

## NZS1170 API Call

There are three different ways of calling NZCode API.

1. Compute Hazard Curve
2. Compute UHS
3. Compute NZS1170

### 1. Compute Hazard Curve

Just like the image below, when **Hazard Curve**'s compute button gets clicked, it sends the first request to get Hazard data then send another request to get the NZ Code data.
![image](https://user-images.githubusercontent.com/7849113/101111598-67126e00-3640-11eb-81ce-2084b171ba69.png)

### 2. Compute UHS

Just like Hazard Curve above, after the app sends a request to get UHS data, it sends another request to get NZ Code data.

### 3. Compute NZS1170

Compute button is disabled until one of **Hazard Curve** or **UHS** gets computed. When one of those get computed, users now can update **Soil Class** and/or **Z Factor** then click Set button to set it then the compute button. It will then update **Hazard Curve** and/or **UHS** NZ Code data without them to be recomputed.

The logic on this compute button is basically:

1. We need to have at least one plot, either **Hazard Curve** or **UHS**
2. **Soil Class** and/or **Z Factor** needs to be set by the Set button (Without clicking set, will not update value)
3. New **Soil Class** and/or **Z Factor** should not be equal to the current NZ Code's parameters.
(For instance, we compute the Hazard Curve with default parameters which are Soil Class - B, Z Factor - 0.3. then until we change either Soil Class and/or Z Factor to something else, Compute will stay disabled as we already used B and 0.3 to get NZ Code data.)

#### Examples

##### Hazard Curve Compute with D - soft or deep soil & 0.3

![image](https://user-images.githubusercontent.com/7849113/101112571-7e525b00-3642-11eb-807e-8a0fe89d9b8b.png)

##### Update Hazard Curve's NZ Code via NZ Code section with A - rock & 0.9

![image](https://user-images.githubusercontent.com/7849113/101112620-9cb85680-3642-11eb-93d3-8bb9e75e6f87.png)

##### UHS Compute with D - soft or deep soil & 0.3

![image](https://user-images.githubusercontent.com/7849113/101113053-6f1fdd00-3643-11eb-938f-8ef845592a1c.png)

##### UHS's NZ Code via NZ Code section with A - rock & 0.9

![image](https://user-images.githubusercontent.com/7849113/101113086-8068e980-3643-11eb-9cde-0131185c3e22.png)

## NZ Code visibility

With the checkbox, we can toggle on/off the NZ Code plot's visibility.

![image](https://user-images.githubusercontent.com/7849113/101113263-e2c1ea00-3643-11eb-90a0-b8bb523f6279.png)

![image](https://user-images.githubusercontent.com/7849113/101113276-e9e8f800-3643-11eb-9d29-97e7ecc96d9d.png)

2020-12-04 02:27 UTC, jasonmotha approved these changes

2020-12-06 19:53 UTC, claudio525 requested changes
See https://github.com/ucgmsim/seistech/pull/335 before this can be merged

2020-12-09 01:12 UTC, sungeunbae commented
Excellent documentation

2020-12-10 21:53 UTC, claudio525 approved these changes

2020-12-10 21:55 UTC, merged