Edit User UI
ucgmsim/seistech_psha_frontend pull request #44
Opened 2021-02-10 22:24 UTC by SnowNooDLe

# Edit User UI

Simple UI for SeisTech team to make life better.

![image](https://user-images.githubusercontent.com/7849113/107577902-e8e1d180-6c57-11eb-9110-33a1d461ab7c.png)

## User dropdown

The list is done by using Auth0's endpoint to grab all the existing users.

![image](https://user-images.githubusercontent.com/7849113/107577973-0020bf00-6c58-11eb-804f-09fdbb77c008.png)

## Project dropdown

Project dropdown will show the list of projects that can be added to the chosen user.

For instance, Brendon will have all five projects but Tom has nothing that can be added.

This is because we compare the list of projects in our DB, `Available_Projects` table to the projects that are returned by the ProjectAPI.

As you can from the image right below, in my localdev DB, it only has five rows for Tom. 

![image](https://user-images.githubusercontent.com/7849113/107578473-aa004b80-6c58-11eb-9205-e6f0e22cc56d.png)

From the image above, localdev DB doesn't have Brendon's available projects, hence we can allocate all five projects to Brendon if we want.

![image](https://user-images.githubusercontent.com/7849113/107578042-1dee2400-6c58-11eb-8abd-da44dd3593cc.png)

Whereas for Tom, I already allocated all five projects to myself, hence no options available.

![image](https://user-images.githubusercontent.com/7849113/107578058-22b2d800-6c58-11eb-95d6-5689734d03a0.png)

## Workflow

1. Select a user from the User dropdown.
2. Select project(s) you want to allocate to the chosen user.
3. Click the Allocate Project button to allocate.

### 1. Select a user from the User dropdown

Remember, the list is coming from the Auth0, not from our DB, hence there may be a case where the DB does not know the chosen users information yet.

For instance, we create an account for Robin & Sarah, then Auth0 knows but our DB until we update. This case, you will still see Robin & Sarah's account under User dropdown.

### 2. Select project(s) you want to allocate to the chosen user.

Continue from 1, if the chosen user is not in the DB, then you will see every project that is currently in the ProjectAPI as the DB does not have any information of the chosen user due to new creation.

### 3. Click the Allocate Project button to allocate

Finally, trying to allocate projects to a new user will do the following steps.

1. Add a chosen user to the DB first as the user is not existing in the DB.
2. Then allocate chosen projects to the chosen user to the DB, available_projects table.

This happens the same to the project if it is not in the DB but exists in the Project API. This process will update the DB then allocate to the chosen. user.

## Examples 1 - User does not exist in the DB yet

User is not there
![Screenshot from 2021-02-11 10-24-18](https://user-images.githubusercontent.com/7849113/107579768-85a56e80-6c5a-11eb-8433-9bee57c0e933.png)

But the user is in the list as it is communicating to the Auth0, not the DB
![Screenshot from 2021-02-11 10-24-38](https://user-images.githubusercontent.com/7849113/107579783-89d18c00-6c5a-11eb-98c6-9f53a3498d1c.png)

Successfully added the chosen projects to the chosen user.
![Screenshot from 2021-02-11 10-24-48](https://user-images.githubusercontent.com/7849113/107579798-8e964000-6c5a-11eb-8a98-0b601f025158.png)

Now the DB also has information about the chosen user.
![Screenshot from 2021-02-11 10-25-03](https://user-images.githubusercontent.com/7849113/107579821-97871180-6c5a-11eb-9909-b8a76031d7fb.png)

Also, the `available_projects` table is updated.
![Screenshot from 2021-02-11 10-25-07](https://user-images.githubusercontent.com/7849113/107580128-fba9d580-6c5a-11eb-93b7-c523077e9cb1.png)

Hence, we only have one project to show as this is the only project that can be added to Tom.
![Screenshot from 2021-02-11 10-24-56](https://user-images.githubusercontent.com/7849113/107579840-9c4bc580-6c5a-11eb-8192-cde63e18660d.png)

## Examples 2 - Project does not exist in the DB yet

Imagine the DB only has four projects.
![Screenshot from 2021-02-11 11-12-43](https://user-images.githubusercontent.com/7849113/107580321-3f044400-6c5b-11eb-900a-ba312d4db26c.png)

Also in the `available_projects` table, Tom only has permission to four projects.
![Screenshot from 2021-02-11 11-12-48](https://user-images.githubusercontent.com/7849113/107580377-517e7d80-6c5b-11eb-8595-408a0a1cce7f.png)

However, ProjectAPI says there are five projects, not four, hence the dropdown will show the fifth option which can be added to Tom.
![Screenshot from 2021-02-11 11-14-05](https://user-images.githubusercontent.com/7849113/107580428-6824d480-6c5b-11eb-9e90-03613d597e37.png)

![Screenshot from 2021-02-11 11-14-10](https://user-images.githubusercontent.com/7849113/107580494-8094ef00-6c5b-11eb-9a05-99d5e4b30d18.png)

The chosen project did not exist in the DB, updating the DB.
![Screenshot from 2021-02-11 11-14-13](https://user-images.githubusercontent.com/7849113/107580519-8db1de00-6c5b-11eb-8ea1-40bb9cfacac9.png)

The DB is updated for both `Project` and `Available_Projects` table.
![Screenshot from 2021-02-11 11-14-23](https://user-images.githubusercontent.com/7849113/107580554-9acecd00-6c5b-11eb-8fc4-b9623767e750.png)
![Screenshot from 2021-02-11 11-14-28](https://user-images.githubusercontent.com/7849113/107580557-9c989080-6c5b-11eb-893c-067126b3f539.png)

2021-02-11 22:52 UTC, claudio525 reviewed
Looks good, have a bunch of comment, pretty much all of them are just style. Just thought it's good to point these out now, especially as you start to do more python.
Additionally I think it would be worth for you to check out type hints (https://realpython.com/lessons/type-hinting/) and docstring format. There are lots different docstring formats, I use the numpy one (you can set this up in pycharm to generate a template automatically), see https://numpydoc.readthedocs.io/en/latest/format.html. I don't follow this super strictly, but I do like having some structure in docstrings. Also, if the function is trivial, then I don't usually worry about a docstring and just add a one liner. But for a function with a lot of arguments and some non-trivial functionality I think it is def worth adding a quality docstring. All about finding a balanced approach for this imo.

2021-02-11 22:52 UTC, claudio525 commented on middleware/middleware/api/middleware_api.py
> +"""MIDDLEWARE API
I think endpoint functions should be at the top and then make all non-endpoint functions protected (i.e. add _ to the front of their name).
Reason: The main purpose of the file is to define/create the endpoints, hence that code should come first. All other functions are helper functions, and if this is only place where you are planning on using them then they should be protected/private. Otherwise they should probably go into another file.

2021-02-11 22:52 UTC, claudio525 commented on middleware/middleware/api/middleware_api.py
> +# Will be uesd for User dropdown
This should be in the function docstring

2021-02-11 22:52 UTC, claudio525 commented on middleware/middleware/api/middleware_api.py
> +# Will be used for Project dropdown
This also belongs in the docstring

2021-02-11 22:52 UTC, claudio525 commented on middleware/middleware/api/middleware_api.py
> +from flask import jsonify, request
Order of imports, https://www.python.org/dev/peps/pep-0008/#imports
I don't follow this super strictly, but I do like the ordering as described here:
```
Imports should be grouped in the following order:

    Standard library imports.
    Related third party imports.
    Local application/library specific imports.

You should put a blank line between each group of imports.
```
Additionally in each block I like having the `import x` ones before the `from x import y` ones.

I.e. I would re-write the below as:
```python
import os
import json
from http import client

import requests
from flask import jsonify, request

from ..server import bla, bla, bla
```

2021-02-11 22:52 UTC, claudio525 commented on middleware/middleware/api/middleware_api.py
> +AUTH0_CLIENT_ID = os.environ["AUTH0_CLIENT_ID"]
I think these belong into server.py and then just import it from there

Also given the number of imports from server.py, it might be worth changing it to
`from .. import server`

2021-02-11 22:52 UTC, claudio525 commented on middleware/middleware/api/middleware_api.py
> +
Unnecessary blank line, you can also define both of these variables in one line:
`user_list, user_dict = resp.json(), {}`

2021-02-11 22:52 UTC, claudio525 commented on middleware/middleware/api/middleware_api.py
> +    # The reason we keep both email and provider is due to preventing confusion based on having the same emails but different provider
This line is probably slightly to long?

2021-02-11 22:52 UTC, claudio525 commented on middleware/middleware/api/middleware_api.py
> +
Don't need a blank line here (since the comment is for the for loop)

2021-02-11 22:52 UTC, claudio525 commented on middleware/middleware/server.py
> +    all_projects_dicts = proxy_to_api(request, "api/project/ids/get", "GET").get_json()
Nothing wrong with what you have, but personally I would make this function a one liner, i.e.
`return  proxy_to_api(request, "api/project/ids/get", "GET").get_json()`

2021-02-11 22:52 UTC, claudio525 commented on middleware/middleware/server.py
> +    It finds available projects from the DB (Available_Project that contains user_id and project_name).
I think this line and 174 are both to long (pycharm should highlight these for you?)

2021-02-11 22:52 UTC, claudio525 commented on middleware/middleware/server.py
> +    It compares the projects between the DB and Project API and return the options that are not in the intersction.
Line length, I think once its over 80 I usually start wrapping

2021-02-11 22:52 UTC, claudio525 commented on middleware/middleware/server.py
> +    if check_user_in_db(user_id) == False:
Slightly better way to write this would be `if not check_user_in_db(..)` and renaming the function to user_in_db or is_user_in_db. Or if you want to be more explicit use `is` instead of `==` for bool checks.

2021-02-11 22:52 UTC, claudio525 commented on middleware/middleware/server.py
> +        db.session.add(new_user)
I would just make this a one-liner, i.e. `db.session.add(User(user_id))`, since the variable is only used once (and the definition is nice and short)

2021-02-11 22:52 UTC, claudio525 commented on middleware/middleware/server.py
> +
No need for a blank line here

2021-02-12 03:33 UTC, jasonmotha submitted a review, later dismissed

2021-02-13 22:42 UTC, claudio525 commented on middleware/middleware/server.py
> +def _get_management_api_token():
Hmh I don't think these functions belong into server.py either, lets talk Monday!

2021-02-14 00:09 UTC, sungeunbae commented
> Additionally I think it would be worth for you to check out type hints (https://realpython.com/lessons/type-hinting/) and docstring format. There are lots different docstring formats, I use the numpy one (you can set this up in pycharm to generate a template automatically), see https://numpydoc.readthedocs.io/en/latest/format.html.

Just out of curiosity - Does VScode have this setup too?

2021-02-14 08:05 UTC, claudio525 commented
@sungeunbae https://github.com/NilsJPWerner/autoDocstring

2021-02-15 02:44 UTC, claudio525 commented on middleware/middleware/service.py
> +import json
I suggest renaming this file to db.py, and moving the functions `requires_permission`, `proxy_to_api` and `get_token_auth_header` to again a separate file called utils.py

2021-02-15 02:44 UTC, claudio525 commented on middleware/middleware/service.py
> +# Create tables - It only creates when tables don't exist
This belongs into server.py
This file should not execute any code, it only defines functions. 
`server.py` on the other hand is where all the setup happens, hence that is where those two lines belong imo.

Usually code files fall into 2 categories,
1) they do something, e.g. a script that is called from the command line (I usually put these under a scripts folder in a python package)
2) module file that contains functions, but doesn't actually do anything when run (These belong in the src folder). And these are the ones that are used by scripts from the package or external of the package)

These are very rough guidelines and its def not as simple as that, but imo its good habit to aim for this. 
`server.py` is one of those weird ones, I kinda think of it as a setup file. If you remind me next time I'm in the office then I can give you a run-down on python package organization (if you want).

seistech internal is probably not a bad example, https://github.com/ucgmsim/seistech/tree/master/seistech_internal/seistech_internal

2021-02-15 02:44 UTC, claudio525 commented on middleware/middleware/api/project_api.py
unnecessary blank line

2021-02-15 02:44 UTC, claudio525 commented on middleware/middleware/api/middleware_api.py
unnecessary blank line

2021-02-15 02:44 UTC, claudio525 commented on middleware/middleware/api/middleware_api.py
> +
unnecessary blank line

2021-02-15 02:44 UTC, claudio525 commented on middleware/middleware/api/core_api.py
unnecessary blank line

2021-02-15 02:44 UTC, claudio525 commented on middleware/middleware/api/core_api.py
> +
unnecessary blank line

2021-02-15 02:57 UTC, jasonmotha requested changes

2021-02-15 02:57 UTC, jasonmotha commented on middleware/middleware/service.py
> +    If it contains projectAPI, we siwtch APIBase to Project API path.
switch

2021-02-15 02:57 UTC, jasonmotha commented on middleware/middleware/service.py
> +                "description": "Authorization header must start with" " Bearer",
Any reason for the split strings?

2021-02-15 20:29 UTC, jasonmotha commented on middleware/middleware/utils.py
> +    # If endpoint is specified, its the one with uesrs' insteaction, record to DB
Sorry for picking up all your spelling mistakes. They just leap out at me when skimming through. 😅

2021-02-15 21:42 UTC, merged