Update GMS in Hazard Analysis tab
ucgmsim/seistech_psha_frontend pull request #54
Opened 2021-03-15 03:07 UTC by SnowNooDLe

# Update GMS in Hazard Analysis tab

## No need to review this request until #53 and #51 goes to the `master_dev`

## Fix the GMS plot - instead of using the user's IM/Exceedance rate level, use the IM_j value from the API.

GMS used to plot with users input when the `IM Type(Conditioning IM Name)` starts with `pSA`. Instead of using the user's input, we used the `im_j` value from the response data(From the Core API).

### Example - Previous version

![image](https://user-images.githubusercontent.com/7849113/111096198-d8e54680-85a3-11eb-91eb-009eb9c816c9.png)

### Example - Current version

![image](https://user-images.githubusercontent.com/7849113/111096447-6cb71280-85a4-11eb-8ad3-06992e3143be.png)

## Remove the `Highlight.js` package as no longer needed.

It used to be used on the `Profile` page. However, this was a default thing from Auth0 and we will have our version of the `Profile` page later.

## Implement the computed GMS data validation
  - Check the IM Type matches with selected Conditioning IM Name
  - Checking its properties
    - To see if any of the properties with 0 lengths (It means no values for this property)
    - To see if some of the properties' properties are matching with the selected IM Vectors
      (For instance, if selected IM Vectors are PGA, pSA_0.01 and pSA_0.02, then properties of `gcim_cdf_x`, `gcim_cdf_y` and `realisations` should match with the selected IM Vectors))
- With the validation above, if something goes wrong, we set the `setShowErrorMessage` to show an error message.
  - Currently, this is more developers-friendly

### Example of error if returned data is not valid

This message can definitely be improved at the point where it's close to the final, stable, production version but for debugging purpose but still can handle error to notify us what went wrong, I think this is enough.

![image](https://user-images.githubusercontent.com/7849113/111096783-2a420580-85a5-11eb-8dab-70c23c9f5a67.png)

## Others - A few updates

1. Order of file's content
    1. React Hook comes first
       - For instance, `useState` and `useEffect`
    2. Any functions
2. Try to avoid declaring variables inside the component(not inside the function)
   - Because React's functional components get re-rendered every time the `useState` gets changed, then by using either `let` or `const` will constantly get called hence, instead of using them, just use `useState` because this hook gets only called once at INITIAL render.
   For instance, instead of having
   ```javascript
     let causalParamBounds = {
      mag: {
        min: GMSMwMin,
        max: GMSMwMax,
      },
      rrup: {
        min: GMSRrupMin,
        max: GMSRrupMax,
      },
      vs30: {
        min: GMSVS30Min,
        max: GMSVS30Max,
        vs30: vs30,
      },
    };

    let filterParamsObj = {
      mag_low: Number(GMSMwMin),
      mag_high: Number(GMSMwMax),
      rrup_low: Number(GMSRrupMin),
      rrup_high: Number(GMSRrupMax),
      vs30_low: Number(GMSVS30Min),
      vs30_high: Number(GMSVS30Max),
    };
   ```
   Now we have this
   ```javascript
     const filterParamsObj = {
        mag_low: Number(GMSMwMin),
        mag_high: Number(GMSMwMax),
        rrup_low: Number(GMSRrupMin),
        rrup_high: Number(GMSRrupMax),
        vs30_low: Number(GMSVS30Min),
        vs30_high: Number(GMSVS30Max),
      };

      // Min/Max values for one of the plots
      // Also only gets called within fetching call(Compute GMS) so doesn't matter with number of render gets done
      setCausalParamBounds({
        mag: {
          min: GMSMwMin,
          max: GMSMwMax,
        },
        rrup: {
          min: GMSRrupMin,
          max: GMSRrupMax,
        },
        vs30: {
          min: GMSVS30Min,
          max: GMSVS30Max,
          vs30: vs30,
        },
      });
   ```
3. Each plot now deals with different CLONED objects
Because JavaScript's Object and Array are by REFERENCE not by VALUE.
Hence by passing/using the object to other functions/variables and if any change made, will affect the original object.
Hence, to prevent any issue, cloned the object(deep copy) for each plot:
    1. IM Distribution
    2. Causal Parameter
    3. MwRrup Plot
    4. Spectra
 
4. Spectra calculation is done somewhere else.
As with re-rendering for functional components, every state gets changed, (even by clicking the dropdown within the `IM Distributions` and `Causal Parameters` tab under the viewer, will make this component re-render because it changes the state.)
The calculation isn't big big but is bigger than any other plots and it certainly takes some time to:
   1. Calculate based on given computed GMS Data
   2. Draw with Plotly.js based on this calculated data 
Hence, instead of calculating within the viewer part, used a function to calculate and store the calculated data into `state` Hence, the component doesn't have to re-calculate every time it gets re-rendered because `useState` only called at the INITIAL render and whenever the `setter` gets called which is inside the fetching call(Computing GMS Data) so unless sending another request to fetch GMS data, this state will never get called again. Hence, the app only needs to deal with drawing plots with `Plotly.js` which we cannot stop doing it.

5. `react-error-overlay` package

We can disable the following error overlay which is only visible on the development but our DEV and EA are running under development. So I thought it would be good to implement this package to disable the error message from the EA version.

![image](https://user-images.githubusercontent.com/7849113/111098287-0207d600-85a8-11eb-997d-cbb124f7dc89.png)

```javascript
if (process.env.REACT_APP_ENV === "EA") {
  stopReportingRuntimeErrors(); // disables error overlays
}
```

2021-03-23 21:14 UTC, jasonmotha requested changes

2021-03-23 21:14 UTC, jasonmotha commented on frontend/src/constants/Constants.js
> +      "Issue found in the retruend data that properties do not match with selected IM Vector",
THere are a few instances with that spelling.

2021-03-23 21:14 UTC, jasonmotha commented on frontend/src/utils/Utils.js
> +// Create an Array from start to stop by step
Again, giving a bit more context with this type of comment. Currently it's basically reiterating the line of code.

2021-03-23 21:14 UTC, jasonmotha commented on frontend/src/utils/Utils.js
> +// Create an special aray for react-select
array - Why do we want a special array.

2021-03-23 21:14 UTC, jasonmotha commented on frontend/src/utils/calculations/CalculateGMSSpectra.js
> +      // With out current format, IM starts with pSA, they have period.
our*
Can also shrink this comment by removing "we" and other conversational english.

2021-03-23 21:14 UTC, jasonmotha commented on frontend/src/utils/calculations/CalculateGMSSpectra.js
> +      So we can plot them in the right order.
Another example of a good comment. But can also shrink the last two lines (you mention the right order 3 times)

2021-03-23 21:14 UTC, jasonmotha commented on frontend/src/utils/calculations/CalculateGMSSpectra.js
> +      // If IM (IM from IM Vectors) is not same as IM_Type, we do different approach.
Better off merging the comments in the block with this comment. What is your different approach?

2021-03-23 21:14 UTC, jasonmotha commented on frontend/src/utils/calculations/CalculateGMSSpectra.js
> +      So we can plot them in the right order.
Because I skim through comments, bullet points work really well.

2021-03-23 21:14 UTC, jasonmotha commented on frontend/src/utils/calculations/CalculateGMSSpectra.js
> +      Same as Realisations caluclation above.
calculation

2021-03-24 19:50 UTC, claudio525 reviewed
Looks good!

2021-03-24 19:50 UTC, claudio525 commented on frontend/src/components/Hazard/GMS/GMSForm.js
> +  const [localMwMin, setLocalMwMin] = useState(CONSTANTS.DEFAULT_MW_MIN);
Huh any specific reason for hardcoding these defaults? Did Brendon ask for this?

2021-03-24 19:50 UTC, claudio525 commented on frontend/src/components/Hazard/GMS/GMSForm.js
>          const newIMVector = Array.from(localIMVector, (x) => x.value);
This line & the two below, look to me like one block of code (create the array,  add the IMs, remove last comma), i.e. the block creates the request url (from my understanding). In which case the empty lines between these lines should be removed, to highlight that these belong together?

2021-03-24 20:50 UTC, SnowNooDLe commented on frontend/src/components/Hazard/GMS/GMSForm.js
>          const newIMVector = Array.from(localIMVector, (x) => x.value);
Correct, they are all doing something for one purpose, adding the right values to the query string.

2021-03-24 22:11 UTC, jasonmotha requested changes

2021-03-24 22:11 UTC, jasonmotha commented on frontend/src/components/Hazard/GMS/GMSViewerCausalParameters.js
> +  // Duplicate the elements except the first and the last element
Nice!

2021-03-24 22:11 UTC, jasonmotha commented on frontend/src/components/Hazard/GMS/GMSViewerCausalParameters.js
> +  // Add bounds (Min / Max)
I would still put these on the same line as they are related.

2021-03-25 01:40 UTC, merged