Project gms
ucgmsim/seistech_psha_frontend pull request #60
Opened 2021-03-25 23:04 UTC by SnowNooDLe

# Projects tab - GMS

Projects GMS is implemented, Tooltips need to be updated also the disclaimer? at some stage.

![image](https://user-images.githubusercontent.com/7849113/112554132-9a188180-8e2a-11eb-8986-3786b5ab53de.png)

![image](https://user-images.githubusercontent.com/7849113/112554144-9f75cc00-8e2a-11eb-8d41-a0fad0184453.png)

![image](https://user-images.githubusercontent.com/7849113/112554151-a43a8000-8e2a-11eb-91f4-a67345e695fd.png)

![image](https://user-images.githubusercontent.com/7849113/112554155-a7ce0700-8e2a-11eb-9bcc-bf1e4debb3af.png)

![image](https://user-images.githubusercontent.com/7849113/112554165-ac92bb00-8e2a-11eb-82c0-5025cbe21327.png)

## .gitignore update - requirements.txt

As we recently changed the workflow of the branches, master_dev and master_ea

master_dev treats as a playground, when a feature seems working, just merge it into master_dev and deploy it to the psha-dev.

Then once it looks good and ready for the review, open PR to master_ea and get a code review.

Hence, the psha-dev will be based on the `master_dev` and the psha-ea will be based on the `master_ea`. Hence the middleware package will be installed from a different branch depends on the deployed branch:
- psha-dev's middleware will be installed from master_dev
- psha-ea's middleware will be installed from master_ea

2021-03-25 23:11 UTC, jasonmotha submitted a review, later dismissed

2021-03-25 23:11 UTC, jasonmotha commented on frontend/src/components/Project/GMS/GMSViewer.js
> +          let queryString = `?project_id=${projectId}&station_id=${projectLocationCode[projectLocation]}_${projectVS30}&gms_id=${projectGMSId}`;
Is there not a query builder? Seems odd that you have to build it manually?

2021-03-25 23:13 UTC, jasonmotha commented on frontend/src/components/Project/GMS/GMSViewer.js
> +  // E.g. change tab between Pojrects and Hazard Analyis
Pojrects -> rekt

2021-03-26 00:42 UTC, claudio525 submitted a review, later dismissed

2021-03-28 19:08 UTC, claudio525 submitted a review, later dismissed

2021-03-28 21:19 UTC, jasonmotha requested changes
Make a function

2021-03-30 00:36 UTC, jasonmotha commented on frontend/src/components/common/GMS/GMSViewerCausalParameters.js
> +  let xAxisRange = [-1, Math.max(...xRange) * 1.1];
xtr_space = Math.max(...xRange) * 0.1
xRange = (0 - xtr_space, xtr_space * 11) 

This should make the spacing on both sides equal? Assuming the axis is linear space.

2021-03-30 00:37 UTC, jasonmotha commented on frontend/src/components/common/GMS/GMSViewerCausalParameters.js
> +      metadata === "mag"
Comment to explain the cases here

2021-03-30 00:39 UTC, SnowNooDLe commented
Close due to more changes to come & prevent sending a notification every time I push.

2021-03-30 00:39 UTC, closed without merging